// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:utility/config.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: Config.apiKey1,
    appId: '1:503589871845:web:4bf0bedfd7b2a8f7deb40c',
    messagingSenderId: '503589871845',
    projectId: 'utility-1ad71',
    authDomain: 'utility-1ad71.firebaseapp.com',
    storageBucket: 'utility-1ad71.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: Config.apiKey2,
    appId: '1:503589871845:android:36e73662be85ddb2deb40c',
    messagingSenderId: '503589871845',
    projectId: 'utility-1ad71',
    storageBucket: 'utility-1ad71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: Config.apiKey3,
    appId: '1:503589871845:ios:a668c78e7d917a75deb40c',
    messagingSenderId: '503589871845',
    projectId: 'utility-1ad71',
    storageBucket: 'utility-1ad71.appspot.com',
    iosBundleId: 'com.example.utility',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: Config.apiKey4,
    appId: '1:503589871845:ios:a668c78e7d917a75deb40c',
    messagingSenderId: '503589871845',
    projectId: 'utility-1ad71',
    storageBucket: 'utility-1ad71.appspot.com',
    iosBundleId: 'com.example.utility',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: Config.apiKey5,
    appId: '1:503589871845:web:282990021bec6cd7deb40c',
    messagingSenderId: '503589871845',
    projectId: 'utility-1ad71',
    authDomain: 'utility-1ad71.firebaseapp.com',
    storageBucket: 'utility-1ad71.appspot.com',
  );
}
